Repository OpenSource-SW-Project/ChatDa, pull requests merged in 2024-06, with the labels that each got.

#58 [feat] 유저가 작성한 일기 조회 API 기능 구현
  src/main/java/Opensource_SW_Project/Project/converter/DiaryConverter.java
  src/main/java/Opensource_SW_Project/Project/repository/DiaryRepository.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryQueryService.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/web/controller/DiaryController.java
  src/main/java/Opensource_SW_Project/Project/web/dto/Diary/DiaryResponseDTO.java
Labels: feat

#60 [feat] 로그인, 회원가입, 인증, 인가 기능 구현
  build.gradle
  src/main/java/Opensource_SW_Project/Project/JWT/CustomUserDetailsService.java
  src/main/java/Opensource_SW_Project/Project/JWT/JwtAuthenticationFilter.java
  src/main/java/Opensource_SW_Project/Project/JWT/JwtTokenProvider.java
  src/main/java/Opensource_SW_Project/Project/config/SecurityConfig.java
  src/main/java/Opensource_SW_Project/Project/config/SwaggerConfig.java
  src/main/java/Opensource_SW_Project/Project/converter/DiaryConverter.java
  src/main/java/Opensource_SW_Project/Project/converter/TalkConverter.java
  src/main/java/Opensource_SW_Project/Project/converter/UserConverter.java
  src/main/java/Opensource_SW_Project/Project/domain/Diary.java
  src/main/java/Opensource_SW_Project/Project/domain/Member.java
  src/main/java/Opensource_SW_Project/Project/domain/Talk.java
  src/main/java/Opensource_SW_Project/Project/domain/User.java
  src/main/java/Opensource_SW_Project/Project/repository/MemberRepository.java
  src/main/java/Opensource_SW_Project/Project/repository/TalkRepository.java
  src/main/java/Opensource_SW_Project/Project/repository/UserRepository.java
  src/main/java/Opensource_SW_Project/Project/service/ChatgptApiService/ChatgptApiServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/TalkService/TalkCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/UserService/MemberCommandService.java
  src/main/java/Opensource_SW_Project/Project/service/UserService/MemberCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/UserService/MemberQueryService.java
  src/main/java/Opensource_SW_Project/Project/service/UserService/MemberQueryServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/UserService/UserCommandService.java
  src/main/java/Opensource_SW_Project/Project/service/UserService/UserCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/web/controller/MemberController.java
  src/main/java/Opensource_SW_Project/Project/web/controller/TalkController.java
  src/main/java/Opensource_SW_Project/Project/web/controller/UserController.java
  src/main/java/Opensource_SW_Project/Project/web/dto/JwtToken.java
  src/main/java/Opensource_SW_Project/Project/web/dto/Member/MemberRequestDTO.java
  src/main/java/Opensource_SW_Project/Project/web/dto/Member/MemberResponseDTO.java
  src/main/java/Opensource_SW_Project/Project/web/dto/User/UserRequestDTO.java
Labels: feat

#63 [feat] 유저가 작성한 일기 조회 API 및 일기생성, 수정 API에 인가 처리 기능 부여
  src/main/java/Opensource_SW_Project/Project/config/SecurityConfig.java
  src/main/java/Opensource_SW_Project/Project/domain/Diary.java
  src/main/java/Opensource_SW_Project/Project/repository/DiaryRepository.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/web/controller/DiaryController.java
Labels: feat

#69 [feat] implement login signup
  src/main/java/Opensource_SW_Project/Project/config/SecurityConfig.java
  src/main/resources/static/css/home.css
  src/main/resources/static/js/config.js
  src/main/resources/static/js/home.js
  src/main/resources/templates/home.html
Labels: feat

#71 [refactor] 유저가 작성한 일기 조회할때 생성 날짜도 함께 조회하도록 수정 / 변수명 수정
  src/main/java/Opensource_SW_Project/Project/JWT/JwtTokenProvider.java
  src/main/java/Opensource_SW_Project/Project/config/SecurityConfig.java
  src/main/java/Opensource_SW_Project/Project/converter/DiaryConverter.java
  src/main/java/Opensource_SW_Project/Project/converter/MemberConverter.java
  src/main/java/Opensource_SW_Project/Project/converter/TalkConverter.java
  src/main/java/Opensource_SW_Project/Project/domain/Diary.java
  src/main/java/Opensource_SW_Project/Project/domain/Member.java
  src/main/java/Opensource_SW_Project/Project/service/ChatgptApiService/ChatgptApiCommandService.java
  src/main/java/Opensource_SW_Project/Project/service/ChatgptApiService/ChatgptApiServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryCommandService.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryQueryService.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/TalkService/TalkCommandService.java
  src/main/java/Opensource_SW_Project/Project/service/TalkService/TalkCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/web/controller/ChatgptApiController.java
  src/main/java/Opensource_SW_Project/Project/web/controller/DiaryController.java
  src/main/java/Opensource_SW_Project/Project/web/controller/MemberController.java
  src/main/java/Opensource_SW_Project/Project/web/controller/TalkController.java
  src/main/java/Opensource_SW_Project/Project/web/dto/Diary/DiaryRequestDTO.java
  src/main/java/Opensource_SW_Project/Project/web/dto/Diary/DiaryResponseDTO.java
  src/main/java/Opensource_SW_Project/Project/web/dto/Member/MemberResponseDTO.java
  src/main/java/Opensource_SW_Project/Project/web/dto/Talk/TalkResponseDTO.java
  src/main/resources/static/js/chat.js
  src/main/resources/static/js/home.js
Labels: refactor

#73 [feat] member diary complete, merge page contoller
  src/main/java/Opensource_SW_Project/Project/config/SecurityConfig.java
  src/main/java/Opensource_SW_Project/Project/web/controller/CalendarController.java
  src/main/java/Opensource_SW_Project/Project/web/controller/PageController.java
  src/main/resources/static/css/calendar.css
  src/main/resources/static/js/calendar.js
  src/main/resources/static/js/home.js
  src/main/resources/templates/calendar.html
  src/main/resources/templates/home.html
Labels: feat

#75 [feat] 회원가입시 아이디 중복 확인 기능 추가
  src/main/java/Opensource_SW_Project/Project/apiPayload/code/status/ErrorStatus.java
  src/main/java/Opensource_SW_Project/Project/apiPayload/exception/handler/MemberHandler.java
  src/main/java/Opensource_SW_Project/Project/service/MemberService/MemberCommandServiceImpl.java
Labels: feat

#77 [feat] add navbar (home, logout)
  src/main/resources/static/css/navbar.css
  src/main/resources/static/js/home.js
  src/main/resources/static/js/navbar.js
  src/main/resources/templates/calendar.html
  src/main/resources/templates/chat.html
  src/main/resources/templates/diary.html
  src/main/resources/templates/home.html
  src/main/resources/templates/temp.html
Labels: feat

#79 [feat] move toggle button into container
  src/main/resources/static/css/calendar.css
  src/main/resources/static/css/home.css
  src/main/resources/static/js/home.js
  src/main/resources/templates/home.html
Labels: feat

#81 [feat] add autorize to talk, end chat and PENGUIN
  src/main/resources/static/css/chat.css
  src/main/resources/static/css/temp.css
  src/main/resources/static/img/pengu.gif
  src/main/resources/static/js/chat.js
  src/main/resources/static/js/home.js
  src/main/resources/static/js/temp.js
  src/main/resources/templates/chat.html
  src/main/resources/templates/home.html
  src/main/resources/templates/temp.html
Labels: feat

#83 [feat] modify diary, hide password input, animation smoothing
  src/main/java/Opensource_SW_Project/Project/config/MvcConfiguration.java
  src/main/resources/static/css/animation.css
  src/main/resources/static/css/home.css
  src/main/resources/static/js/temp.js
  src/main/resources/templates/home.html
  src/main/resources/templates/temp.html
Labels: feat

#85 [feat] create writing stle page
  src/main/java/Opensource_SW_Project/Project/config/SecurityConfig.java
  src/main/java/Opensource_SW_Project/Project/web/controller/PageController.java
  src/main/resources/static/css/home.css
  src/main/resources/static/css/writing-style.css
  src/main/resources/static/js/home.js
  src/main/resources/static/js/writing-style.js
  src/main/resources/templates/home.html
  src/main/resources/templates/writing-style.html
Labels: feat

#101 [feat] apply create style api, add button disabled style, smooth login
  src/main/resources/static/css/home.css
  src/main/resources/static/css/temp.css
  src/main/resources/static/css/writing-style.css
  src/main/resources/static/js/home.js
  src/main/resources/static/js/writing-style.js
  src/main/resources/templates/home.html
  src/main/resources/templates/writing-style.html
Labels: feat

#102 [refactor] 사용자가 문체 생성을 여러번할때, 생성 결과가 누적되는 것이 아닌 업데이트 되도록 코드 수정
  src/main/java/Opensource_SW_Project/Project/repository/StyleRepository.java
  src/main/java/Opensource_SW_Project/Project/service/StyleService/StyleCommandService.java
  src/main/java/Opensource_SW_Project/Project/service/StyleService/StyleCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/StyleService/StyleQueryService.java
  src/main/java/Opensource_SW_Project/Project/service/StyleService/StyleQueryServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/web/controller/StyleController.java
Labels: refactor

#105 [refactor] 유저의 문체를 조회할 때 리스트가 아닌 형태로 받아오게 수정
  src/main/java/Opensource_SW_Project/Project/converter/StyleConverter.java
  src/main/java/Opensource_SW_Project/Project/service/StyleService/StyleQueryService.java
  src/main/java/Opensource_SW_Project/Project/service/StyleService/StyleQueryServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/web/controller/StyleController.java
Labels: refactor

#107 [feat] style load api apply
  src/main/resources/static/css/writing-style.css
  src/main/resources/static/js/home.js
  src/main/resources/static/js/writing-style.js
  src/main/resources/templates/home.html
  src/main/resources/templates/writing-style.html
Labels: feat

#109 [feat] detailed_talk테이블에 대화순서 나타내주는 column인 talk_number추가
  src/main/java/Opensource_SW_Project/Project/domain/DetailedTalk.java
  src/main/java/Opensource_SW_Project/Project/repository/DetailedTalkRepository.java
  src/main/java/Opensource_SW_Project/Project/service/ChatgptApiService/ChatgptApiServiceImpl.java
Labels: feat, refactor

#112 [feat] 대화의 현재 state를 대화생성 api의 response에 추가하기
  src/main/java/Opensource_SW_Project/Project/domain/enums/TalkState.java
  src/main/java/Opensource_SW_Project/Project/web/controller/ChatgptApiController.java
  src/main/java/Opensource_SW_Project/Project/web/dto/ChatgptApi/ChatgptApiResponseDTO.java
Labels: feat

#116 [feat] 문체 다이어리에 적용하기 및 문체 적용된 다이어리, 문체 적용되지 않은 다이어리 모두 생성
  src/main/java/Opensource_SW_Project/Project/converter/DiaryConverter.java
  src/main/java/Opensource_SW_Project/Project/domain/Diary.java
  src/main/java/Opensource_SW_Project/Project/repository/DiaryRepository.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryCommandService.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/EmbeddingService/EmbeddingService.java
  src/main/java/Opensource_SW_Project/Project/web/controller/DiaryController.java
  src/main/java/Opensource_SW_Project/Project/web/dto/Diary/DiaryResponseDTO.java
Labels: feat

#118 [feat] 대화 화제 개수에 따라서 대화 종료 조건 확인하는 기능 추가
  src/main/java/Opensource_SW_Project/Project/domain/DetailedTalk.java
  src/main/java/Opensource_SW_Project/Project/service/ChatgptApiService/ChatgptApiCommandService.java
  src/main/java/Opensource_SW_Project/Project/service/ChatgptApiService/ChatgptApiServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/web/controller/ChatgptApiController.java
Labels: feat

#119 [bug] fix load writing style
  src/main/resources/static/css/home.css
  src/main/resources/static/js/home.js
Labels: bug

#122 [refactor] 일기 생성 api 에러 해결
  src/main/java/Opensource_SW_Project/Project/repository/DiaryRepository.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/Opensource_SW_Project/Project/web/controller/DiaryController.java
Labels: refactor

#123 [feat] coloring, natural exit
  src/main/java/Opensource_SW_Project/Project/service/ModerationService/ModerationServicelmpl.java
  src/main/resources/static/css/calendar.css
  src/main/resources/static/css/chat.css
  src/main/resources/static/css/home.css
  src/main/resources/static/img/exit.png
  src/main/resources/static/js/chat.js
  src/main/resources/templates/calendar.html
  src/main/resources/templates/chat.html
Labels: feat

#125 [feat] two result
  src/main/resources/static/css/temp.css
  src/main/resources/static/js/calendar.js
  src/main/resources/static/js/chat.js
  src/main/resources/static/js/temp.js
  src/main/resources/templates/temp.html
Labels: feat

#127 [refactor] Rename README.md to DEMO_README.md
  DEMO_README.md
Labels: refactor

#128 [feat] Create README.md
  README.md
Labels: feat

#129 [refactor] Update README.md
  README.md
Labels: refactor

#131 [refactor] Update README.md
  README.md
Labels: refactor

#134 [refactor] 대화 화제 전환 프롬프트 수정
  src/main/java/Opensource_SW_Project/Project/service/ChatgptApiService/ChatgptApiServiceImpl.java
Labels: refactor

#135 Update README.md
  README.md
Labels: refactor
